"""
export_gru_weights.py  (v2 -- hard-activation aware)
Exports a trained GRU checkpoint to:
  1. weights_flat.bin  - flat FP32 buffer in HLS layout order (5201 floats)
  2. golden_input.bin  - FP32 test input samples
  3. golden_output.bin - FP32 PyTorch reference output (CPU, authoritative path)
Layout contract (must match gru_va.h):
  w_ih[3H] -> w_hh[3H][H] row-major -> b_ih[3H] -> b_hh[3H] -> w_out[H] -> b_out[1]
PyTorch gate row order is r, z, n - same as the header assumes.

v2 change: reads the checkpoint's 'act' field (written by finetune_hard.py).
  act == "exact" / absent -> golden via torch.nn.GRU (unchanged pinned path)
  act == "hard"           -> golden via GRUVAManual(act="hard"), i.e.
                             Hardsigmoid/Hardtanh (DPD eq. 7/8) matching the
                             Hard* HLS kernel. Prevents the mismatch where a
                             hard checkpoint gets a true-tanh golden.
The stimulus is unchanged and deterministic (seeded), so golden_input.bin is
bit-identical across all exports; only weights + golden output vary.
"""

import argparse
import numpy as np
import torch

H = 40


def emit_header(outdir, w_ih, w_hh, b_ih, b_hh, w_out, b_out):
    """Write gru_parameters.h in the class parameters.h style:
    const float arrays, one per tensor, named to match the kernel.
    Gate row order in the source tensors: r (0:H), z (H:2H), n (2H:3H)."""
    H = 40

    def arr1(name, v):
        vals = ", ".join(f"{x:.9g}f" for x in v)
        return f"const float {name}[{len(v)}] = {{ {vals} }};\n"

    def arr2(name, m):
        rows = ",\n    ".join(
            "{ " + ", ".join(f"{x:.9g}f" for x in row) + " }" for row in m
        )
        return f"const float {name}[{m.shape[0]}][{m.shape[1]}] = {{\n    {rows}\n}};\n"

    w_ih_f = w_ih.flatten()
    parts = [
        "// gru_parameters.h - auto-generated by export_gru_weights.py\n",
        "// DO NOT EDIT. Regenerate from the canonical checkpoint.\n",
        "// Gate convention: PyTorch/cuDNN (reset applied AFTER recurrent matmul).\n",
        "// Layout matches weights_flat.bin: same tensors, unpacked per-gate.\n",
        "#ifndef GRU_PARAMETERS_H\n#define GRU_PARAMETERS_H\n\n",
        arr1(
            "Wr_param", w_ih_f[0:H]
        ),  # 0 to 3*H is because they all share a vector w_ih_f
        arr1("Wz_param", w_ih_f[H : 2 * H]),
        arr1("Wn_param", w_ih_f[2 * H : 3 * H]),
        arr2(
            "Ur_param", w_hh[0:H, :]
        ),  # 0 to 3*H is because they all share a vector w_ih_h
        arr2("Uz_param", w_hh[H : 2 * H, :]),
        arr2("Un_param", w_hh[2 * H : 3 * H, :]),
        arr1(
            "b_ir_param", b_ih[0:H]
        ),  # 0 to 3*H is because they all share a vector b_ih
        arr1("b_iz_param", b_ih[H : 2 * H]),
        arr1("b_in_param", b_ih[2 * H : 3 * H]),
        arr1(
            "b_hr_param", b_hh[0:H]
        ),  # 0 to 3*H is because they all share a vector b_hh
        arr1("b_hz_param", b_hh[H : 2 * H]),
        arr1("b_hn_param", b_hh[2 * H : 3 * H]),
        arr1("w_out_param", w_out),
        arr1("b_out_param", b_out),
        "\n#endif // GRU_PARAMETERS_H\n",
    ]
    path = f"{outdir}/gru_parameters.h"
    with open(path, "w") as f:
        f.writelines(parts)
    print(f"gru_parameters.h: written ({H=}, PyTorch gate convention)")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--n-samples", type=int, default=4096)
    p.add_argument("--outdir", default=".")
    p.add_argument(
        "--emit-header",
        action="store_true",
        help="also write gru_parameters.h (compiled-weights style)",
    )
    args = p.parse_args()

    ckpt = torch.load(args.checkpoint, map_location="cpu", weights_only=False)

    # v2: activation mode travels with the checkpoint (finetune_hard.py writes
    # act="hard"; train_spike.py checkpoints have no field -> "exact").
    act = ckpt.get("act", "exact") if isinstance(ckpt, dict) else "exact"

    sd = (
        ckpt["model"]
        if isinstance(ckpt, dict) and "model" in ckpt
        else ckpt["state_dict"]
        if isinstance(ckpt, dict) and "state_dict" in ckpt
        else ckpt
    )
    if not isinstance(sd, dict) or not any(hasattr(v, "shape") for v in sd.values()):
        sd = sd.state_dict()  # a full module was saved

    print(f"activation mode: {act}")
    print("State-dict keys found:")
    for k, v in sd.items():
        print(f"  {k}: {tuple(v.shape)}")

    # ---- Locate tensors by shape (robust to naming) ----
    def find(shape):
        hits = [k for k, v in sd.items() if tuple(v.shape) == shape]
        if len(hits) != 1:
            raise SystemExit(
                f"Expected exactly one tensor of shape {shape}, found {hits}. "
                f"Edit the key mapping manually."
            )
        return sd[hits[0]].detach().cpu().numpy().astype(np.float32)

    w_ih = find((3 * H, 1))  # gru.weight_ih_l0
    w_hh = find((3 * H, H))  # gru.weight_hh_l0
    biases = [k for k, v in sd.items() if tuple(v.shape) == (3 * H,)]
    if len(biases) != 2:
        raise SystemExit(f"Expected two (120,) bias tensors, found {biases}")
    # ih bias sorts before hh bias in PyTorch naming (bias_ih_l0 < bias_hh_l0 is FALSE
    # alphabetically - so match by substring, not sort order)
    b_ih_key = [k for k in biases if "ih" in k]
    b_hh_key = [k for k in biases if "hh" in k]
    if len(b_ih_key) != 1 or len(b_hh_key) != 1:
        raise SystemExit(f"Could not disambiguate ih/hh biases from {biases}")
    b_ih = sd[b_ih_key[0]].detach().cpu().numpy().astype(np.float32)
    b_hh = sd[b_hh_key[0]].detach().cpu().numpy().astype(np.float32)

    w_out = find((1, H)).flatten()  # linear output weight
    b_out_hits = [k for k, v in sd.items() if tuple(v.shape) == (1,)]
    if len(b_out_hits) != 1:
        raise SystemExit(f"Expected one (1,) output bias, found {b_out_hits}")
    b_out = sd[b_out_hits[0]].detach().cpu().numpy().astype(np.float32)

    # ---- Flatten in header layout order ----
    flat = np.concatenate(
        [
            w_ih.flatten(),  # 120   (3H x 1, row-major = same as column)
            w_hh.flatten(),  # 4800  (row-major: row i = all H recurrent weights of gate-row i)
            b_ih,  # 120
            b_hh,  # 120
            w_out,  # 40
            b_out,  # 1
        ]
    ).astype(np.float32)
    assert flat.size == 5201, f"Layout size {flat.size} != 5201"
    flat.tofile(f"{args.outdir}/weights_flat.bin")

    if args.emit_header:
        emit_header(args.outdir, w_ih, w_hh, b_ih, b_hh, w_out, b_out)

    print(f"weights_flat.bin: {flat.size} floats")

    # ---- Golden vectors: reference forward pass on CPU ----
    torch.manual_seed(0)
    # Test signal: 1 kHz sine at -12 dBFS + a burst of noise (exercises nonlinearity)
    t = np.arange(args.n_samples) / 48000.0
    x = 0.25 * np.sin(2 * np.pi * 1000.0 * t).astype(np.float32)
    x[2048:] += 0.1 * np.random.default_rng(0).standard_normal(
        args.n_samples - 2048
    ).astype(np.float32)
    xt = torch.from_numpy(x).reshape(1, -1, 1)

    if act == "hard":
        # Hard-activation checkpoint: golden MUST use the same Hardsigmoid /
        # Hardtanh forms as the HLS kernel, via the manual cell.
        from gru_cell_manual import GRUVAManual

        model = GRUVAManual(hidden=H, skip=False, act="hard")
        model.load_state_dict(sd, strict=True)
        model.eval()
        with torch.no_grad():
            yt, _ = model(xt)  # h=None -> zero init (matches reset_state=1)
        y = yt.flatten().numpy().astype(np.float32)
        print("golden path: GRUVAManual(act='hard')  [Hardsigmoid/Hardtanh]")
    else:
        gru = torch.nn.GRU(input_size=1, hidden_size=H, batch_first=True)
        lin = torch.nn.Linear(H, 1)
        with torch.no_grad():
            gru.weight_ih_l0.copy_(torch.from_numpy(w_ih))
            gru.weight_hh_l0.copy_(torch.from_numpy(w_hh))
            gru.bias_ih_l0.copy_(torch.from_numpy(b_ih))
            gru.bias_hh_l0.copy_(torch.from_numpy(b_hh))
            lin.weight.copy_(torch.from_numpy(w_out.reshape(1, H)))
            lin.bias.copy_(torch.from_numpy(b_out))
            h0 = torch.zeros(1, 1, H)
            hseq, _ = gru(xt, h0)  # CPU path = authoritative (standing convention)
            y = lin(hseq).flatten().numpy().astype(np.float32)
        print("golden path: torch.nn.GRU  [exact sigmoid/tanh]")

    x.tofile(f"{args.outdir}/golden_input.bin")
    y.tofile(f"{args.outdir}/golden_output.bin")
    print(f"golden_input.bin / golden_output.bin: {args.n_samples} samples each")
    print(
        f"output range: [{y.min():.4f}, {y.max():.4f}]  "
        f"(check this fits DT_ACT integer bits)"
    )


if __name__ == "__main__":
    main()
